[program:pds-pusher-server]
command=node --no-deprecation pulse-server-js start
directory=/var/www/pulse/bundle
autostart=true
autorestart=true
user=wahyupds
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/pulse/bundle/logs/supervisor.log
stopasgroup=true
killasgroup=true

# Jika menggunakan environment variables tambahan
# environment=NODE_ENV="production"
