[program:pds-pusher-server]
command=node --no-deprecation pusher-server-js start
directory=/mnt/dm-0/DEVELOPMENT-SPECIAL/pds-pusher-server/bundle
autostart=true
autorestart=true
user=wahyupds
numprocs=1
redirect_stderr=true
stdout_logfile=/mnt/dm-0/DEVELOPMENT-SPECIAL/pds-pusher-server/bundle/logs/supervisor.log
stopasgroup=true
killasgroup=true

# Jika menggunakan environment variables tambahan
# environment=NODE_ENV="production"
